---
- name: grafana - check if sources have been downloaded
  stat: path=~/src/{{ GRAFANA_SOURCE_FILENAME }}.deb
  register: grafana_download

- name: grafana - update repo
  shell: sudo apt-get update

- name: grafana - install requierment
  shell: sudo apt-get install -y adduser libfontconfig

- name: grafana - download package
  shell: wget https://grafanarel.s3.amazonaws.com/builds/{{ GRAFANA_SOURCE_FILENAME }}.deb
  when: not grafana_download.stat.exists
  args:
    chdir: ~/src

- name: grafana - install
  shell: dpkg -i ~/src/{{ GRAFANA_SOURCE_FILENAME }}.deb

- name: grafana - start service
  service: name=grafana-server state=started

- name: grafana - wait for service
  wait_for: port=3000 delay=5
